@baseUrl = http://127.0.0.1:8000


### Demo - Chat  
POST {{baseUrl}}/agent/chat
Content-Type: application/json

{
  "message": "Simulate 10,000 rolls of two six-sided dice and estimate the probability distribution of their sum. Show me a bar chart.",
  "thread_id": ""
}

### Demo - Chat  
POST {{baseUrl}}/agent/chat
Content-Type: application/json

{
  "message": "What is the weather forecast for today in New York City?",
  "thread_id": ""
}

### Demo - Chat  
POST {{baseUrl}}/agent/chat
Content-Type: application/json

{
  "message": "Which team won the 2025 NCAA basketball championship?",
  "thread_id": ""
}

### Demo - Chat File
POST {{baseUrl}}/agent/chat
Content-Type: application/json

{
  "message": "How do I change the oil? Use the provided manual.",
  "file" : "2019-Ford-Ranger-Owners-Manual.pdf",
  "thread_id": ""
}

### Demo - Chat File
POST {{baseUrl}}/agent/chat
Content-Type: application/json

{
  "message": "What is the part number for the oil filter?",
  "thread_id": "thread_TyFQT3SeYMShnNeik8EHHaSF"
}

### Demo - Chat File
POST {{baseUrl}}/agent/chat
Content-Type: application/json

{
  "message": "Plesse describe the damage to the car",
  "file" : "car1.jpg",
  "thread_id": ""
}
